#Create deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
      app: backend
  template:
    metadata:
      name: app
      labels:
        name: app
        app: backend
    spec:
      containers:
        - name: app-deploy
          image: ikmaz2023/spring-boot-app:01
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: password

---
#Create a service
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30010
  selector:
    name: app
    app: backend